// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockJob;

namespace StockJob.Migrations
{
    [DbContext(typeof(StockDBContext))]
    partial class StockDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PersonalAssistant.Models.StockInfo", b =>
                {
                    b.Property<int>("StockInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<decimal>("HighestPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("LastTradedPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int>("LastVolume")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitDown")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("LimitUp")
                        .HasColumnType("decimal(16,2)");

                    b.Property<decimal>("LowestPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("OpeningPrice")
                        .HasColumnType("decimal(16,2)");

                    b.Property<DateTime>("SyncTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalVolume")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("YesterdayClosingPrice")
                        .HasColumnType("decimal(16,2)");

                    b.HasKey("StockInfoID");

                    b.ToTable("StockInfo");
                });

            modelBuilder.Entity("PersonalAssistant.Models.Top5Buy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int?>("StockInfoID")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StockInfoID");

                    b.ToTable("Top5Buy");
                });

            modelBuilder.Entity("PersonalAssistant.Models.Top5Sell", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(16,2)");

                    b.Property<int?>("StockInfoID")
                        .HasColumnType("int");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StockInfoID");

                    b.ToTable("Top5Sell");
                });

            modelBuilder.Entity("PersonalAssistant.Models.Top5Buy", b =>
                {
                    b.HasOne("PersonalAssistant.Models.StockInfo", null)
                        .WithMany("Top5Buy")
                        .HasForeignKey("StockInfoID");
                });

            modelBuilder.Entity("PersonalAssistant.Models.Top5Sell", b =>
                {
                    b.HasOne("PersonalAssistant.Models.StockInfo", null)
                        .WithMany("Top5Sell")
                        .HasForeignKey("StockInfoID");
                });
#pragma warning restore 612, 618
        }
    }
}
